### ISSUE TITLE
Scribble V2

### ISSUE THREAD

**Issue by yedhink** [udai1931/scribble-by-udai-gupta#69]
- [x] Edit Navbar for Dashboard
- [x] Add version history UI
- [x] Add backend for version history
- [x] Add Search function in EUI sidebar
- [x] Add visits count in backend and then in UI

- [x] Add Analytics Page UI
- https://www.loom.com/share/4968f64edcfb456193922bb0128d44fb
- https://www.figma.com/file/Sd50nrJ4nfcJNohMRPNXNk/Scribble?node-id=5084%3A2496

@udai1931 _a This is a `epic` issue. Epic issue needs be divided into atomic sub issues. You can raise the sub issues and list it in the first comment by editing the first comment itself, as checkbox items.

Once all the sub-issues are closed, then only the `epic` should be closed.

Lemme know if you have any queries.
